# Introduction {.unnumbered}

This is a book to take you from the basics of GitHub through the more complicated bits that arise as you try to use GitHub for daily work.

This book is in early development.


## Great intro git and GitHub resources:

[Integrating RStudio with a new or existing GitHub repository](https://www.youtube.com/watch?v=sxErFMF7BJY) (18-min video by Riffomonas Project)

[Git for R Users](https://www.youtube.com/watch?v=njMEXGfUQG8) (14-min video by Equitable Equations)

[Happy Git with R](https://happygitwithr.com/) (online text by Jenny Bryan)

[Connecting an existing RStudio project to git and GitHub](https://www.youtube.com/watch?v=bUoN85QvC10) (10-min video by Riffomonas Project)

- Tools > Version Control > Project Setup, set Version control system to Git, and you’ll get a Git tab (this initializes a local git repo for your R project
- Create a GitHub account if you haven’t already
- Create a new repo on GitHub: set Repository name, add a Description, skip the checkboxes since your local repo will already have a .gitignore file
- Follow the GitHub instructions: click the Copy icon, and paste it into your R Studio terminal (not console)
- Refresh the page for your GitHub repo and you should see all the files




## Additional resources if you want to go deeper into git and GitHub:

[Git for R users: branches and merges](https://www.youtube.com/watch?v=kN9UZLgxCso) (12-min video by Equitable Equations)

- Use present tense with commit messages
- Branches are great for experimenting with a new feature or a change you think you might want to make
- Instead of making a copy of a file so you can safely tinker with it
- git merge sandbox —message “merge sandbox to main”
- Check out the commit history and look at the graph
- If you’re done with the branch, delete it via git branch -d sandbox
- Resolving merge conflicts is something you might need in the future if you collaborate or if you work on multiple branches of your work simultaneously

[git/GitHub tutorial with command line only](https://www.youtube.com/watch?v=DnwEaa5QtpI) (40-min video by Riffomonas Project)

[Using GitHub Pages](https://www.youtube.com/watch?v=5XhxR9Vs6zc) (7-min video by The Common Coder, uses VS Code)

- GitHub pages are static sites (no user input, but you can still have minimal interactivity). you get one main site per account, https://github-username.github.io, and unlimited project sites https://github-username.github.io/project-name
- Under your repo, go to settings > pages
- Source: choose either deploy from a branch or github actions
- What actions looks like (yellow turns to either green checkmark or red x)
- Go back to settings > page and it says “your site is live at …”

[Using GitHub pages to host a web page made with R Markdown](https://www.youtube.com/watch?v=ozta7H7WK58&t=51s) (24-min video by Riffomonas Project, in VS Code)

- Settings > Pages > deploy from a branch, main, root
- He makes an index.Rmd file with output html_document and github_repo <url>
- This video uses CSS and Snakemake as well as command-line git
- This video shows some nice tips on using CSS and Rmarkdown variables to improve your page
- He also made a [super cool followup video](https://www.youtube.com/watch?v=t1MGEVeTgQM) to show how you can use Snakemake to have your webpage get updated every day!
